jest.mock(
	'gflow-config',
	() => ( {
		script_debug: '1',
		hmr_dev: '0',
		grids: {
			inbox_default: {
				grid_options: {
					columnDefs: [
						{
							headerName: 'ID',
							field: 'id',
							filter: 'agTextColumnFilter',
							minWidth: 50,
							sortable: true,
							compareType: 'int',
							sortKey: 'id',
							resizable: true,
							display: true,
						},
						{
							headerName: 'Form',
							field: 'form_title',
							filter: 'agTextColumnFilter',
							minWidth: 200,
							sortable: true,
							compareType: 'string',
							sortKey: 'form_title',
							resizable: true,
							display: true,
						},
						{
							headerName: 'Submitter',
							field: 'created_by',
							filter: 'agTextColumnFilter',
							minWidth: 100,
							sortable: true,
							compareType: 'string',
							sortKey: 'created_by',
							resizable: true,
							display: true,
						},
						{
							headerName: 'Step',
							field: 'workflow_step',
							filter: 'agTextColumnFilter',
							minWidth: 50,
							sortable: true,
							compareType: 'string',
							sortKey: 'workflow_step',
							resizable: true,
							display: true,
						},
						{
							headerName: 'Submitted',
							field: 'date_created',
							filter: 'agTextColumnFilter',
							minWidth: 100,
							sortable: true,
							compareType: 'date',
							sortKey: 'date_created_timestamp',
							resizable: true,
							display: true,
						},
					],
					rowData: [
						{
							id: '148',
							form_title: 'Parent Form',
							created_by: 'sam',
							workflow_step: 'Loan Review',
							date_created: '2021-06-05 at 5:39 pm',
							date_created_timestamp: 1622914794,
						},
						{
							id: '115',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:13 pm',
							date_created_timestamp: 1616955187,
						},
						{
							id: '114',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:13 pm',
							date_created_timestamp: 1616955182,
						},
						{
							id: '113',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:12 pm',
							date_created_timestamp: 1616955157,
						},
						{
							id: '111',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:12 pm',
							date_created_timestamp: 1616955136,
						},
						{
							id: '110',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:12 pm',
							date_created_timestamp: 1616955131,
						},
						{
							id: '109',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:12 pm',
							date_created_timestamp: 1616955128,
						},
						{
							id: '108',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:12 pm',
							date_created_timestamp: 1616955123,
						},
						{
							id: '107',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:11 pm',
							date_created_timestamp: 1616955119,
						},
						{
							id: '106',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:09 pm',
							date_created_timestamp: 1616954976,
						},
						{
							id: '105',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:09 pm',
							date_created_timestamp: 1616954971,
						},
						{
							id: '104',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:09 pm',
							date_created_timestamp: 1616954956,
						},
						{
							id: '103',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:09 pm',
							date_created_timestamp: 1616954952,
						},
						{
							id: '102',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:09 pm',
							date_created_timestamp: 1616954947,
						},
						{
							id: '101',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:09 pm',
							date_created_timestamp: 1616954942,
						},
						{
							id: '100',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:08 pm',
							date_created_timestamp: 1616954937,
						},
						{
							id: '99',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954798,
						},
						{
							id: '98',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954795,
						},
						{
							id: '97',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954791,
						},
						{
							id: '96',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954787,
						},
						{
							id: '95',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954782,
						},
						{
							id: '94',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954779,
						},
						{
							id: '93',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:06 pm',
							date_created_timestamp: 1616954764,
						},
						{
							id: '92',
							form_title: 'List Field',
							created_by: 'sam',
							workflow_step: 'Test',
							date_created: '2021-03-28 at 6:05 pm',
							date_created_timestamp: 1616954749,
						},
					],
					pagination: true,
					paginationPageSize: 20,
				},
				current_user_token:
					'eyJpYXQiOjE2MjQ4MzI0MTUsImV4cCI6MTYyNzQyNDQxNSwic3ViIjoidXNlcl9pZHwxIiwic2NvcGVzIjp7InBhZ2VzIjpbImluYm94Iiwic3RhdHVzIl0sInVzZXJfaWQiOjF9LCJqdGkiOiI2MGQ4Zjk5ZjljZGFhIn0%3D.404986f2ee1b05cdc7e677092d90f1b68b2ab49c27323e7d1e07239ccd3405e1',
				fetch_enabled: true,
				fetch_interval: 30,
				default_sort_col: 'id',
				default_sort_dir: 'asc',
			},
		},
	} ),
	{ virtual: true }
);
